# Site settings
title: Petr Motlicek
email: petr dot motlicek ad idiap dot ch
description: > # this means to ignore newlines until "baseurl:"
  I'm a permanent researcher at Idiap Research Institute.  
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://www.idiap.ch/~pmotlic" # the base hostname & protocol for your site
skype_username: motlicek
#permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
